CREATE TYPE "SubjectType" AS ENUM ('OBLIGATORIA', 'OPTATIVA', 'PROFUNDIZACION', 'TRANSVERSAL', 'DIMENSION');
CREATE TYPE "EducationLevel" AS ENUM ('PREESCOLAR', 'PRIMARIA', 'SECUNDARIA', 'MEDIA');
CREATE TYPE "ClassroomType" AS ENUM ('AULA', 'LAB_FISICA', 'LAB_QUIMICA', 'COMPUTO', 'CANCHA', 'AUDITORIO');
CREATE TYPE "CourseDirectorStatus" AS ENUM ('ACTIVE', 'INACTIVE');