export const PERMISSIONS = {
  INSTITUTION_READ: 'institution:read',
  INSTITUTION_UPDATE: 'institution:update',
  INSTITUTION_MANAGE: 'institution:manage',
  USERS_READ: 'users:read',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  USERS_MANAGE: 'users:manage',
  MEMBERSHIPS_READ: 'memberships:read',
  MEMBERSHIPS_MANAGE: 'memberships:manage',
  ROLES_READ: 'roles:read',
  ROLES_MANAGE: 'roles:manage',
  STUDENTS_READ: 'students:read',
  STUDENTS_MANAGE: 'students:manage',
  COURSES_READ: 'courses:read',
  COURSES_MANAGE: 'courses:manage',
  SUBJECTS_READ: 'subjects:read',
  SUBJECTS_MANAGE: 'subjects:manage',
  GRADES_READ: 'grades:read',
  GRADES_MANAGE: 'grades:manage',
  SCHEDULES_READ: 'schedules:read',
  SCHEDULES_MANAGE: 'schedules:manage',
  TASKS_READ: 'tasks:read',
  TASKS_CREATE: 'tasks:create',
  TASKS_UPDATE: 'tasks:update',
  TASKS_DELETE: 'tasks:delete',
  TASKS_MANAGE: 'tasks:manage',
  COMMUNICATIONS_READ: 'communications:read',
  COMMUNICATIONS_CREATE: 'communications:create',
  COMMUNICATIONS_MANAGE: 'communications:manage',
  COMMUNICATIONS_SEND_BULK: 'communications:send_bulk',
  SIGNATURES_READ: 'signatures:read',
  SIGNATURES_REQUEST: 'signatures:request',
  SIGNATURES_SIGN: 'signatures:sign',
  SIGNATURES_MANAGE: 'signatures:manage',
  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_MANAGE: 'notifications:manage',
  AUDIT_READ: 'audit:read',
  FILES_UPLOAD: 'files:upload',
  FILES_READ: 'files:read',
  FILES_MANAGE: 'files:manage',
  SCHOOL_GRADES_READ: 'school-grades:read',
  SCHOOL_GRADES_MANAGE: 'school-grades:manage',
  ACADEMIC_PERIODS_READ: 'academic-periods:read',
  ACADEMIC_PERIODS_MANAGE: 'academic-periods:manage',
  GUARDIANS_READ: 'guardians:read',
  GUARDIANS_MANAGE: 'guardians:manage',
  ENROLLMENTS_READ: 'enrollments:read',
  ENROLLMENTS_MANAGE: 'enrollments:manage',
  TEACHER_ASSIGNMENTS_READ: 'teacher-assignments:read',
  TEACHER_ASSIGNMENTS_MANAGE: 'teacher-assignments:manage',
  AGENDA_READ: 'agenda:read',
  STUDENT_FOLLOW_UPS_READ: 'student-follow-ups:read',
  STUDENT_FOLLOW_UPS_CREATE: 'student-follow-ups:create',
  STUDENT_FOLLOW_UPS_UPDATE: 'student-follow-ups:update',
  STUDENT_FOLLOW_UPS_CLOSE: 'student-follow-ups:close',
  STUDENT_FOLLOW_UPS_ESCALATE: 'student-follow-ups:escalate',
  STUDENT_FOLLOW_UPS_FOLLOW_UP: 'student-follow-ups:follow_up',
  STUDENT_FOLLOW_UPS_COMMIT: 'student-follow-ups:commit',
  STUDENT_FOLLOW_UPS_ATTACH: 'student-follow-ups:attach',
  STUDENT_FOLLOW_UPS_MANAGE: 'student-follow-ups:manage',
  STUDENT_FOLLOW_UPS_STATS: 'student-follow-ups:stats',
  STUDENT_FOLLOW_UPS_CATEGORIES: 'student-follow-ups:categories',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_NAMES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  INSTITUTION_ADMIN: 'INSTITUTION_ADMIN',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
} as const;
