export const PERMISSIONS = {
  INSTITUTION_READ: 'institution:read',
  INSTITUTION_MANAGE: 'institution:manage',
  USERS_READ: 'users:read',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  USERS_MANAGE: 'users:manage',
  MEMBERSHIPS_READ: 'memberships:read',
  MEMBERSHIPS_MANAGE: 'memberships:manage',
  STUDENTS_READ: 'students:read',
  STUDENTS_MANAGE: 'students:manage',
  COURSES_READ: 'courses:read',
  COURSES_MANAGE: 'courses:manage',
  SUBJECTS_READ: 'subjects:read',
  SUBJECTS_MANAGE: 'subjects:manage',
  GRADES_READ: 'grades:read',
  GRADES_MANAGE: 'grades:manage',
  SCHEDULES_READ: 'schedules:read',
  SCHEDULES_MANAGE: 'schedules:manage',
  TASKS_READ: 'tasks:read',
  TASKS_MANAGE: 'tasks:manage',
  COMMUNICATIONS_READ: 'communications:read',
  COMMUNICATIONS_MANAGE: 'communications:manage',
  SIGNATURES_READ: 'signatures:read',
  SIGNATURES_REQUEST: 'signatures:request',
  SIGNATURES_SIGN: 'signatures:sign',
  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_MANAGE: 'notifications:manage',
  SCHOOL_GRADES_READ: 'school-grades:read',
  SCHOOL_GRADES_MANAGE: 'school-grades:manage',
  ACADEMIC_PERIODS_READ: 'academic-periods:read',
  ACADEMIC_PERIODS_MANAGE: 'academic-periods:manage',
  GUARDIANS_READ: 'guardians:read',
  GUARDIANS_MANAGE: 'guardians:manage',
  ENROLLMENTS_READ: 'enrollments:read',
  ENROLLMENTS_MANAGE: 'enrollments:manage',
  TEACHER_ASSIGNMENTS_READ: 'teacher-assignments:read',
  TEACHER_ASSIGNMENTS_MANAGE: 'teacher-assignments:manage',
  FILES_READ: 'files:read',
  FILES_UPLOAD: 'files:upload',
  FILES_MANAGE: 'files:manage',
  AGENDA_READ: 'agenda:read',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_NAMES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  INSTITUTION_ADMIN: 'INSTITUTION_ADMIN',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
} as const;
