export const ASSIGNABLE_TENANT_ROLES: string[] = [
  'INSTITUTION_ADMIN',
  'TEACHER',
  'PARENT',
  'STUDENT',
  'RECTOR',
  'COORDINADOR_ACADEMICO',
  'COORDINADOR_CONVIVENCIA',
  'ORIENTADOR',
  'PSICOLOGO',
  'DIRECTOR_DE_GRUPO',
];
